on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [zcs-event-sca-maven]
  pull_request: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  semgrep-sca-maven:
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Semgrep SCA Maven
        run: |
          # Replace 'https://' with 'https://{PAT}@' in the GIT_URL
          modified_url=$(echo "${GIT_URL}" | sed "s|https://|https://${PAT_READ_ONLY_CUSTOMER_REPO}@|")
          
          echo "Original URL: ${GIT_URL}"
          echo "Modified URL: ${modified_url}"
          echo "Repo Name: ${REPOSITORY_NAME}"
          echo "Repo Full Name: ${SEMGREP_REPO_NAME}"
          git clone ${modified_url} cloned-repo          
          # show directory contents of root folder
          ls -l cloned-repo
          git config --global --add safe.directory /__w/nn-zcs/nn-zcs
          cd cloned-repo
          git status
          export SEMGREP_REPO_NAME=$SEMGREP_REPO_NAME
          export SEMGREP_REPO_URL=$GIT_URL
          export SEMGREP_BRANCH=$SEMGREP_BRANCH
          if [ -f "pom.xml" ]; then
            rm -f ~/.m2/settings.xml
            mvn clean install -Dmaven.test.skip=true
            mvn dependency:tree -DskipTests=true -DoutputFile=maven_dep_tree.txt
            semgrep ci --supply-chain
          else 
            echo "No pom.xml found for this repo"
          fi
        env:
          # SEMGREP_REPO_NAME: ${{REPOSITORY_NAME}}
          # SEMGREP_REPO_URL: ${{GIT_URL}}
          GIT_URL: ${{ github.event.client_payload.git_url }}
          REPOSITORY_NAME: ${{ github.event.client_payload.repository_name }}
          PAT_READ_ONLY_CUSTOMER_REPO: ${{ secrets.PAT_READ_ONLY_CUSTOMER_REPO }}
          SEMGREP_REPO_URL: ${{ github.event.client_payload.git_url }}
          SEMGREP_REPO_NAME: ${{ github.event.client_payload.repository_full_name }}
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_BRANCH: ${{ github.event.client_payload.repository_default_branch }}

